name = "text-summarizer-worker"
main = "index.js"
compatibility_date = "2025-06-12"
account_id = "TU_ACCOUNT_ID"

# Si quieres usar variables de entorno en el worker:
# [vars]
# CF_API_TOKEN = ""
# CF_ACCOUNT_ID = ""